<?php

$landingPages = [
    'appliance-repair-manhattan' => [
        'slug' => 'appliance-repair-manhattan',
        'title' => 'Appliance Repair Manhattan',
        'description' => 'Same-day appliance repair service for homes and businesses across Manhattan.',
        'eyebrow' => 'Manhattan Service Page',
        'headline' => 'Appliance Repair Manhattan - Same Day Service Available',
        'subheadline' => 'Licensed technicians for refrigeration, cooking, dish care, and laundry equipment across Manhattan homes, condos, and commercial spaces.',
        'service_area' => 'Serving Manhattan neighborhoods including Upper East Side, Tribeca, Chelsea, SoHo, Midtown, and Lower Manhattan.',
        'image' => 'assets/images/Manhattan-Appliance-LLC-020.jpg',
        'trust' => ['Licensed and insured', '90-day warranty on completed repairs', 'Residential and commercial service'],
        'problems' => ['Refrigerator not cooling', 'Oven not heating evenly', 'Dishwasher leaking or not draining', 'Washer or dryer not completing cycles'],
        'why' => ['Fast dispatch within Manhattan service routes', 'Clear communication before arrival', 'Experience in high-rise and luxury residential buildings'],
        'cta_copy' => 'Call now or send a service request for fast Manhattan scheduling.',
        'form_title' => 'Request Manhattan Service',
        'testimonial' => ['quote' => 'Very professional service.', 'author' => 'M, Chris', 'source' => 'Via HCP - 10/19/2025'],
        'related' => ['sub-zero-repair-nyc', 'miele-repair-nyc', 'viking-repair-nyc'],
    ],
    'appliance-repair-new-jersey' => [
        'slug' => 'appliance-repair-new-jersey',
        'title' => 'Appliance Repair New Jersey',
        'description' => 'Appliance repair service for select New Jersey counties and nearby service areas.',
        'eyebrow' => 'New Jersey Service Page',
        'headline' => 'Appliance Repair New Jersey - Fast Regional Scheduling',
        'subheadline' => 'Professional appliance diagnostics and repair for select New Jersey service areas, with direct coordination through our Manhattan office.',
        'service_area' => 'Serving approved ZIP codes in select New Jersey counties. Check your ZIP code or contact us for confirmation.',
        'image' => 'assets/images/shutterstock_1081332008.jpg',
        'trust' => ['Scheduled appointment windows', 'Same professional standards as Manhattan calls', 'Coverage verified by service-area ZIP list'],
        'problems' => ['Cooktop ignition issues', 'Dryer not heating', 'Ice maker performance problems', 'Commercial refrigeration downtime'],
        'why' => ['ZIP-based service confirmation', 'Structured appointment routing', 'Residential and commercial support'],
        'cta_copy' => 'Use the ZIP checker or contact the office to confirm New Jersey availability.',
        'form_title' => 'Request New Jersey Service',
        'testimonial' => ['quote' => 'They got a complicated job done.', 'author' => 'Lorenzo Bautista', 'source' => 'Via Google - 11/21/2025'],
        'related' => ['appliance-repair-manhattan', 'service-areas', 'services'],
    ],
    'sub-zero-repair-nyc' => [
        'slug' => 'sub-zero-repair-nyc',
        'title' => 'Sub-Zero Repair NYC',
        'description' => 'Sub-Zero refrigerator, freezer, and ice maker repair in Manhattan, NYC.',
        'eyebrow' => 'Brand-Specific Landing Page',
        'headline' => 'Sub-Zero Repair NYC - Same Day Service Available',
        'subheadline' => 'Certified support for Sub-Zero refrigeration systems in Manhattan, with fast response for cooling failures, ice maker issues, and temperature instability.',
        'service_area' => 'Focused on Manhattan appointments with booking coordination for approved nearby service areas.',
        'image' => 'assets/images/GB+Domestic+Appliance+Repairs-011.jpg',
        'trust' => ['Luxury appliance specialists', 'Fast response for premium refrigeration', 'Service structured for Manhattan properties'],
        'problems' => ['Unit not cooling', 'Ice maker not producing ice', 'Error codes or alarms', 'Compressor and sealed-system symptoms'],
        'why' => ['Brand-focused diagnostics', 'Clear repair recommendations', 'Experienced with built-in premium refrigeration'],
        'cta_copy' => 'Call for urgent Sub-Zero cooling problems or book online now.',
        'form_title' => 'Request Sub-Zero Service',
        'testimonial' => ['quote' => 'Excellent attention to detail and always go above and beyond.', 'author' => 'Stefanie Faris', 'source' => 'Via Google - 11/04/2025'],
        'related' => ['miele-repair-nyc', 'viking-repair-nyc', 'appliance-repair-manhattan'],
    ],
    'miele-repair-nyc' => [
        'slug' => 'miele-repair-nyc',
        'title' => 'Miele Repair NYC',
        'description' => 'Miele appliance repair in Manhattan, NYC for dishwashers, laundry, and cooking equipment.',
        'eyebrow' => 'Brand-Specific Landing Page',
        'headline' => 'Miele Repair NYC - Premium Appliance Support',
        'subheadline' => 'Targeted Miele repair for dishwashers, ovens, washers, dryers, and other premium appliances throughout Manhattan.',
        'service_area' => 'Designed for Manhattan homeowners, property managers, and businesses that need premium appliance support.',
        'image' => 'assets/images/Manhattan-Appliance-LLC-020.jpg',
        'trust' => ['Premium appliance experience', 'Clean, mobile-first scheduling flow', 'Fast call-back and booking coordination'],
        'problems' => ['Dishwasher not draining', 'Washer displaying error codes', 'Dryer heating issues', 'Oven temperature inconsistency'],
        'why' => ['Structured troubleshooting for premium brands', 'Professional communication from booking through visit', 'Residential and multi-unit service support'],
        'cta_copy' => 'Send a quick service request or book online for Miele repair in Manhattan.',
        'form_title' => 'Request Miele Service',
        'testimonial' => ['quote' => 'Knowledgeable, communicative and friendly service.', 'author' => 'J B', 'source' => 'Via Google - 11/03/2025'],
        'related' => ['sub-zero-repair-nyc', 'viking-repair-nyc', 'appliance-repair-manhattan'],
    ],
    'viking-repair-nyc' => [
        'slug' => 'viking-repair-nyc',
        'title' => 'Viking Repair NYC',
        'description' => 'Viking appliance repair in Manhattan, NYC for ranges, ovens, cooktops, and refrigeration.',
        'eyebrow' => 'Brand-Specific Landing Page',
        'headline' => 'Viking Repair NYC - Fast Help for Premium Cooking Appliances',
        'subheadline' => 'Service for Viking ranges, ovens, cooktops, and refrigeration systems throughout Manhattan, with clear scheduling and repeat CTA paths.',
        'service_area' => 'Best fit for Manhattan bookings and premium kitchens across residential and commercial environments.',
        'image' => 'assets/images/shutterstock_1081332008.jpg',
        'trust' => ['Premium cooking appliance focus', 'Residential and commercial support', 'Call-first layout built for quick conversions'],
        'problems' => ['Range not igniting', 'Oven not heating', 'Cooktop burner issues', 'Built-in refrigeration performance problems'],
        'why' => ['Experience with high-end cooking equipment', 'Action-focused page structure for fast contact', 'Strong support for complex kitchens'],
        'cta_copy' => 'Call now for urgent Viking issues or request service online.',
        'form_title' => 'Request Viking Service',
        'testimonial' => ['quote' => 'Very professional service.', 'author' => 'M, Chris', 'source' => 'Via HCP - 10/19/2025'],
        'related' => ['sub-zero-repair-nyc', 'miele-repair-nyc', 'appliance-repair-manhattan'],
    ],
];
